#!/usr/bin/python
import os;
import subprocess;
import sys;
import re;

executable = './testhttp_raw'
accept = '127.0.0.1:3333'

def print_usage():
    print("Usage: {} <cookies file> <test http address>".format(sys.argv[0]))
    exit(1)

if len(sys.argv) < 3:
    print_usage()

cookie_file, http_address = sys.argv[-2:]

reg = re.match("^(https?:\/\/)([^:/]+):?(\d+)?.*$", http_address)

if not reg:
    print_usage()

secure = "https" in reg.group(1)
connection_address = reg.group(2) + ':' + (reg.group(3) if reg.group(3) else '443' if secure else '80')

config = """[service]
client = yes
accept = {}
connect = {}
""".format(accept, connection_address)

if secure:
    p = subprocess.Popen("stunnel -fd 0", stdin=subprocess.PIPE, shell=True)
    p.stdin.write(config.encode('utf-8'))
    p.stdin.close()

subprocess.call(args=[executable, accept if secure else connection_address, cookie_file, http_address])

